/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meige_rtspservice_rtsp_RTSPService */

#ifndef _Included_com_meige_rtspservice_rtsp_RTSPService
#define _Included_com_meige_rtspservice_rtsp_RTSPService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meige_rtspservice_rtsp_RTSPService
 * Method:    classInitNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meige_rtspservice_rtsp_RTSPService_classInitNative
  (JNIEnv *, jclass);

/*
 * Class:     com_meige_rtspservice_rtsp_RTSPService
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meige_rtspservice_rtsp_RTSPService_initNative
  (JNIEnv *, jobject);

/*
 * Class:     com_meige_rtspservice_rtsp_RTSPService
 * Method:    startNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meige_rtspservice_rtsp_RTSPService_startNative
  (JNIEnv *, jobject);

/*
 * Class:     com_meige_rtspservice_rtsp_RTSPService
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meige_rtspservice_rtsp_RTSPService_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_meige_rtspservice_rtsp_RTSPService
 * Method:    cleanupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meige_rtspservice_rtsp_RTSPService_cleanupNative
  (JNIEnv *, jobject);

/*
 * Class:     com_meige_rtspservice_rtsp_RTSPService
 * Method:    setNativeFrame
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_meige_rtspservice_rtsp_RTSPService_setNativeFrame
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
